name: pharrell
favicon: null
layout_spectrum: 0
typography_spectrum: 0.25135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c151c'
    - '#fcfbcc'
    - '#1b529b'
    - '#fbb70d'
    - '#94cdd4'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
