name: pharrell
favicon: null
layout_spectrum: 0.59008
typography_spectrum: 0.25135
title: the blacker the berry
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c151c'
    - '#fcfbcc'
    - '#1b529b'
    - '#fbb70d'
    - '#94cdd4'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 1
purpose: []
