name: pharrell
favicon: null
layout_spectrum: 0.90152
typography_spectrum: 0.25135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c8c8d2'
    - '#708482'
    - '#5c5461'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
