name: pharrell
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c8c8d2'
    - '#708482'
    - '#5c5461'
  brandStrength: 0.1875
  lightness: 0.7528429562225938
  saturation: 0.3125
  rhythmicContrast: 0.4840635508298874
purpose: []
